dataset_path: /mnt/hdd/datasets/shapenet2-sd-photo/02958343

experiment: fast_dev
seed: null
save_epoch: 1
sanity_steps: 1
max_epoch: 250
scheduler: null
val_check_percent: 1.0
val_check_interval: 1
resume: null
split_file: splits/cars.txt

num_mapping_layers: 8
lr_g: 0.002
lr_d: 0.002
lazy_gradient_penalty_interval: 16
lazy_path_penalty_after: 0
lazy_path_penalty_interval: 4
latent_dim: 512
lambda_gp: 0.0256
lambda_plp: 2
ada_start_p: 0.  #to disable set to -1
ada_target: 0.6
ada_interval: 4
ada_fixed: False
generator: stylegan2

image_size: 256
num_eval_images: 256
num_vis_images: 256
batch_size: 64
batch_gpu: 16
num_workers: 8
num_devices: 1 # Number of GPUs to use

compile: True

wandb_main: False
suffix: ''

hydra:
  output_subdir: null # Disable saving of config files. We'll do that ourselves.
  run:
    dir: .
